apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pgadmin-ingress
  namespace: prod
spec:
  rules:
  - host: pgadmin-basic.com
    http:
      paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: pgadmin-production
              port:
                number: 80
