apiVersion: v1
kind: Service
metadata:
  name: pgadmin-{{ .Values.env }}
  labels:
    app: pgadmin
    env: {{ .Values.env }}

spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: pgadmin
    env: {{ .Values.env }}
  sessionAffinity: None
  type: NodePort
