apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: gitlab
  name: projected-secrets
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/mint/Documents/K8s/volumes/data"
